'use strict';
const canvas=document.getElementById('particle-canvas'),ctx=canvas.getContext('2d');
const trigger=document.getElementById('sakura-trigger'),hud=document.getElementById('sakura-hud'),hideBtn=document.getElementById('custom-btn-hide'),activeBtn=document.getElementById('custom-btn-active');
let particles=[],state='home',balance='0',latestResultData=null,cachedPeriod=null,cachedNumber=null,shufflerInterval=null;
const URL_REGISTER='https://www.yaarwin.cc/#/register?invitationCode=881272429794',URL_WINGO='https://www.yaarwin.cc/#/saasLottery/WinGo?gameCode=WinGo_30S&lottery=WinGo',URL_RECHARGE='https://www.yaarwin.cc/#/wallet/Recharge';
const modes=['NUM','BIG/SMALL','COLOR'];let currentModeIndex=0;
function resizeCanvas(){canvas.width=hud.clientWidth;canvas.height=hud.clientHeight}function spawnParticles(){particles=[];for(let i=0;i<28;i++)particles.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,s:Math.random()*1.6+.5,v:Math.random()*.35+.12,a:Math.random()*Math.PI*2,o:Math.random()*.6+.2})}function animateParticles(){ctx.clearRect(0,0,canvas.width,canvas.height);particles.forEach(p=>{p.y+=p.v;p.x+=Math.sin(p.a)*.25;p.a+=.02;if(p.y>canvas.height+5){p.y=-5;p.x=Math.random()*canvas.width}ctx.beginPath();ctx.arc(p.x,p.y,p.s,0,Math.PI*2);ctx.fillStyle=`rgba(50,230,242,${p.o})`;ctx.fill()});requestAnimationFrame(animateParticles)}
function openPanel(){trigger.style.display='none';hud.style.display='block';resizeCanvas();spawnParticles()}function closePanel(){hud.style.display='none';trigger.style.display='grid'}
trigger.addEventListener('click',()=>{if(trigger.dataset.dragged!=='true')openPanel()});hideBtn.addEventListener('click',closePanel);
function getOverlayScale(){const c=document.getElementById('my_cyber_overlay_container');if(c&&c.style.transform.includes('scale')){const m=c.style.transform.match(/scale\(([^)]+)\)/);return m?parseFloat(m[1])||1:1}return 1}
function makeDraggable(el,handle,isLauncher){let dragging=false,sx=0,sy=0,ix=0,iy=0;handle.addEventListener('touchstart',start,{passive:false});function start(e){if(e.target.closest('button'))return;dragging=true;if(isLauncher)el.dataset.dragged='false';sx=e.touches[0].clientX;sy=e.touches[0].clientY;ix=el.offsetLeft;iy=el.offsetTop;el.style.left=ix+'px';el.style.top=iy+'px';document.addEventListener('touchmove',move,{passive:false});document.addEventListener('touchend',end)}function move(e){if(!dragging)return;const scale=getOverlayScale(),dx=(e.touches[0].clientX-sx)/scale,dy=(e.touches[0].clientY-sy)/scale;if(Math.abs(dx)>5||Math.abs(dy)>5){if(isLauncher)el.dataset.dragged='true';e.preventDefault()}const maxX=window.innerWidth/scale-el.offsetWidth,maxY=window.innerHeight/scale-el.offsetHeight;el.style.left=Math.max(0,Math.min(ix+dx,maxX))+'px';el.style.top=Math.max(0,Math.min(iy+dy,maxY))+'px'}function end(){dragging=false;document.removeEventListener('touchmove',move);document.removeEventListener('touchend',end)}}makeDraggable(trigger,trigger,true);makeDraggable(hud,hud,false);
setInterval(()=>document.getElementById('ping-text').textContent=Math.floor(Math.random()*40+20)+'ms',2000);function setAccuracy(n){document.getElementById('acc-text').textContent=n+'%';document.getElementById('acc-bar').style.width=n+'%'}function getP(){const d=new Date(),u=new Date(d.getTime()+d.getTimezoneOffset()*60000),tm=u.getHours()*60+u.getMinutes();return u.getFullYear()+String(u.getMonth()+1).padStart(2,'0')+String(u.getDate()).padStart(2,'0')+'1000'+(10001+tm)}async function fetchRealPeriod(){try{const r=await fetch('https://draw.ar-lottery01.com/WinGo/WinGo_1M/GetHistoryIssuePage.json');const d=await r.json();if(d?.data?.list?.length)return{period:d.data.list[0].issueNumber}}catch(e){}return null}function genResultText(n,m){const big=n>=5,word=big?'BIG':'SMALL';if(m==='NUM')return word+' '+n;if(m==='BIG/SMALL')return word;return n===0||n===5?'VIOLET':n%2===0?'RED':'GREEN'}
async function startHack(){if(state==='scanning')return;state='scanning';render();const stages=['INIT','TRACING...','LOCKING...','BYPASS...','DECRYPT...','LOCKED'],main=document.getElementById('readout-main-txt'),sub=document.getElementById('readout-sub-txt');let pct=0;shufflerInterval=setInterval(()=>{pct=Math.min(100,pct+Math.floor(Math.random()*15+5));const stage=stages[Math.min(stages.length-1,Math.floor(pct/100*(stages.length-1)))];main.textContent=Math.floor(Math.random()*10);sub.textContent='CALIBRATING: '+pct+'% | '+stage;setAccuracy(Math.floor(Math.random()*60)+30)},100);const fetched=await Promise.race([fetchRealPeriod(),new Promise(r=>setTimeout(()=>r(null),3000))]);const base=fetched?.period?.toString()||getP();let next=base;try{next=(BigInt(base)+1n).toString()}catch(e){}const num=cachedPeriod===next?cachedNumber:Math.floor(Math.random()*10);cachedPeriod=next;cachedNumber=num;const out=genResultText(num,modes[currentModeIndex]);setTimeout(()=>{clearInterval(shufflerInterval);latestResultData={out,p:next,num};state='result';render()},3500)}
window.route=(r,bal)=>{if(state==='scanning'||state==='result'&&r==='wingo')return;state=r;balance=bal||'0';render()};function go(url){window.open(url,'_blank','noopener,noreferrer')}
function render(){const title=document.getElementById('display-hud-subtitle'),main=document.getElementById('readout-main-txt'),sub=document.getElementById('readout-sub-txt'),core=document.getElementById('fx-core'),aura=document.getElementById('fx-aura');activeBtn.disabled=false;activeBtn.classList.remove('is-active');activeBtn.onclick=null;main.style.animation='none';sub.style.animation='none';main.style.opacity='1';sub.style.opacity='1';aura.style.animation='none';main.style.color='var(--white)';main.style.textShadow='0 0 20px var(--cyan)';
if(state==='reg'){title.textContent='ACCESS GATE';main.textContent='SYSTEM LOCKED';sub.textContent='REGISTRATION REQUIRED';core.style.opacity='.25';setAccuracy(0);activeBtn.innerHTML='REGISTER <span>↗</span>';activeBtn.onclick=()=>go(URL_REGISTER)}else if(state==='home'){title.textContent='CONTROL SURFACE';main.textContent='OPEN WINGO';sub.textContent='₹'+balance+' AVAILABLE';core.style.opacity='.25';setAccuracy(0);activeBtn.innerHTML='OPEN WINGO <span>↗</span>';activeBtn.onclick=()=>go(URL_WINGO)}else if(state==='waiting'){title.textContent='DEPOSIT REQUIRED';main.textContent='LOW BALANCE';sub.textContent='WALLET: ₹'+balance;core.style.opacity='.25';setAccuracy(0);activeBtn.innerHTML='DEPOSIT NOW <span>↗</span>';activeBtn.onclick=()=>go(URL_RECHARGE)}else if(state==='wingo'){title.textContent='ENGINE ONLINE';main.textContent='ENGINE READY';sub.textContent='READY FOR DISCOVERY';core.style.opacity='.6';setAccuracy(0);activeBtn.innerHTML='RUN SCAN <span>↗</span>';activeBtn.onclick=startHack}else if(state==='scanning'){title.textContent='DECRYPTING NODE';core.style.opacity='.95';activeBtn.textContent='SCANNING...';activeBtn.disabled=true}else if(state==='result'){if(!latestResultData){state='wingo';render();return}const n=latestResultData.num,color=n===0||n===5?'#b689ff':n%2===0?'#ff5b83':'#59f2ba';title.textContent='ID: '+(latestResultData.p?latestResultData.p.slice(-4):'----');main.textContent=n;main.style.fontSize='48px';main.style.color=color;main.style.textShadow=`0 0 20px ${color},0 0 40px ${color}`;main.style.opacity='0';sub.textContent=n>=5?'BIG':'SMALL';sub.style.fontSize='16px';sub.style.color='#fff';sub.style.opacity='0';core.style.opacity='.38';aura.style.setProperty('--aura-color',color);aura.style.animation='resultPulse 2s ease-out infinite';setAccuracy(Math.floor(Math.random()*15)+85);setTimeout(()=>{main.style.animation='resultIn .65s cubic-bezier(.175,.885,.32,1.275) forwards';sub.style.animation='subIn .8s cubic-bezier(.175,.885,.32,1.275) forwards'},80);activeBtn.classList.add('is-active');activeBtn.innerHTML='NEXT PREDICTION <span>↗</span>';activeBtn.onclick=startHack}}
window.addEventListener('resize',resizeCanvas);window.addEventListener('load',()=>{render();animateParticles()});
